### ISSUE TITLE
collapse whitespace to minimum needed

### ISSUE THREAD

**Issue by pascalpp** [arcanis/eslint-plugin-arca#1]
(capturing this as an issue, I'll see if I can make a PR for it myself. haven't done eslint dev before.)

say you have some imports:
```
import { Fragment } from 'react';
import React        from 'react';
```

and you add a longer one:
```
import { BusinessChooser } from './BusinessChooser';
import { Fragment } from 'react';
import React        from 'react';
```

with fix on save, the imports are realigned correctly:
```
import { BusinessChooser } from './BusinessChooser';
import { Fragment }        from 'react';
import React               from 'react';
```

but if you then remove the long import:
```
import { Fragment }        from 'react';
import React               from 'react';
```

the imports are left with extra space which is not corrected on fix. as it's common to add an import and then remove it during the course of development, this leads to commit diffs that are purely whitespace.

would be nice if the fix logic for this plugin could collapse the whitespace to the minimum needed for alignment, so that adding and removing a longer import would not leave any whitespace artifacts.

**Comment by arcanis** [comment]
That would make sense - I think this should be implemented by fixing how [`getMaxColumn`](https://github.com/arcanis/eslint-plugin-arca/blob/master/lib/rules/import-align.js#L137) is computed. It currently uses the beginning of the `from` token, but should instead use the end of the previous token.

**Comment by pascalpp** [comment]
Oh cool, I'll take a stab at that.
