### ISSUE TITLE
Prettier conflict 

### ISSUE THREAD

**Issue by wesleymostien** [arcanis/eslint-plugin-arca#11]
How can I make this work with Prettier (in VSCode) ?

If I save a file, for a moment it renders the "arca/import-align" rule correctly, but then Prettier reformats it (I guess) back to 'normal'.

Is this possible?

**Comment by arcanis** [comment]
Some rules are compatible with Prettier (like sorting the imports), others not (like aligning them). That's the problem of Prettier; it's doesn't integrate amazingly well with other automated rules 😕

**Comment by wesleymostien** [comment]
Is it possible to format code without Prettier? Can ESLint do this? I am not quite sure....

**Comment by arcanis** [comment]
Sure it can - many rules have autofixes (all those with [a checkmark](https://eslint.org/docs/rules/#possible-errors)). It's a bit more work to find all those that makes a decent autoformatting experience, but you have more control.
